### ISSUE TITLE
create tidy_ard_row_order() helper 

### ISSUE THREAD

**Issue by bzkrouse** [insightsengineering/cards#104]
goal and use would be similar to tidy_ard_column_order(). Maybe a dplyr::arrange starting with the top level group -> lowest level group, variable, and variable_level in that order?

**Comment by ddsjoberg** [comment]
Sounds good! We just need to be careful not to rearrange rows within a variable's levels

**Comment by ddsjoberg** [comment]
I remembered that `flatter_ard()` ended with an `arrange()`. Not necessarily suggesting this ordering, but could be helpful.

```r
dplyr::arrange(dplyr::pick(dplyr::any_of("variable")),
                    dplyr::pick(dplyr::matches("^group[0-9]+$")),
                    dplyr::pick(dplyr::matches("^group[0-9]+_level$")))
```

Also, the selectors have been rewritten this the above code was written, and can be simplified with

```r
dplyr::arrange(dplyr::pick(all_ard_variables(TRUE, FALSE)),
                    dplyr::pick(all_ard_groups(TRUE, FALSE)),
                    dplyr::pick(all_ard_groups(FALSE, TRUE)))
```

I think the fewer times we write those regular expression matches the better 😆

**Comment by bzkrouse** [comment]
Should this function be applied at the end of every ard_* function like the column ordering? If so is there a reason to keep them separate or should there be a single ordering function?

**Comment by ddsjoberg** [comment]
🤔 I don't think it needs to be at the end of every `ard_*()` function. For example, the variables appear in the order they are passed in the `variables=` argument, which I think makes sense. Similar for the `by=`/`strata=` arguments.

I think where this is would primarily be used is after various ARD outputs are stacked with `bind_ard()` ? What do you think?

**Comment by ddsjoberg** [comment]
TODO:
Add argument to optionally retain ordering of the data from before stacking. For example, we could take distinct() grouping and variable columns, then left merge the full ARD with this to move like-statistics together (e.g. moving t-test AGE results to be near the summary stats for AGE).

**Comment by bzkrouse** [comment]
@ddsjoberg Looking at this again - is the "order of the data" always meaningful? for example:

1. current behavior of ard_categorical is to sort by all_ard_groups() and all_ard_variables() at the end so everything is sorted alphabetically
2. current behavior of ard_continuous is to sort by all_ard_groups() at the end so all groups are sorted alphabetically and variables appear in the order you specify in the original call

which do we want?

**Comment by ddsjoberg** [comment]
At the end of the day, I don't think the sorting matters much either way.

I thought we discussed potentially removing that ordering that is coded into the functions (i had forgotten it was even there!), and adding this function that would do some intentional ordering?

**Comment by bzkrouse** [comment]
"I thought we discussed potentially removing that ordering that is coded into the functions (i had forgotten it was even there!)" <- okay this makes more sense, sorry to forget that detail!
