### ISSUE TITLE
Duplicated informations (analysis population header count)

### ISSUE THREAD

**Issue by aassuied-ps** [insightsengineering/cards#200]
### Feature description

CDISC ARD template provides the analysis population information (header) once (see [FDA STF.xlsx on cdisc-org GitHub](https://github.com/cdisc-org/analysis-results-standard/blob/main/workfiles/examples/ARS%20v1/FDA%20STF.xlsx), on the **AnalysisResults** tab) : 

![image](https://github.com/insightsengineering/cards/assets/123543888/e2984088-62a4-4bf7-a029-132ed7a52ea5)

{cards} provides the frequencies for all variables and variable levels. Here's an example : 

```
# Libraries -----

# install.packages("devtools")
# remotes::install_github("insightsengineering/cards")

library(cards)
library(gtsummary)

# Table -----

## Analysis population -----
ADSLs <- cards::ADSL %>% dplyr::filter(SAFFL == "Y")

## Output -----
tbl <- ADSLs %>%
  gtsummary::tbl_summary(include = c(AGEGR1, DURDSGR1), by = ARM) %>%
  gtsummary::add_overall(last = TRUE)

print(tbl)

# ARD -----

## Without using cards::ard_stack() -----
ARD_1 <-
  cards::bind_ard(
    ard_categorical(ADSLs, by = "ARM", variables = c("AGEGR1", "DURDSGR1")),
    ard_categorical(ADSLs, variables = c("AGEGR1", "DURDSGR1"))
  )

pARD_1 <- ARD_1 %>% dplyr::filter(stat_label == "N") %>% dplyr::arrange(.cols = group1_level)
print(pARD_1)

## Using cards::ard_stack() -----
ARD_2 <-
  cards::ard_stack(
    data = ADSLs,
    by = ARM,
    .overall = TRUE,
    ard_categorical(variables = c("AGEGR1", "DURDSGR1"))
  )

pARD_2 <- ARD_2 %>% dplyr::filter(stat_label == "N") %>% dplyr::arrange(.cols = group1_level)
print(pARD_2)
```

Could we discuss about a way to have the information only once and grab it to construct the tables?

**Comment by aassuied-ps** [comment]
Thanks @ddsjoberg for the answer. Yes it does but I od not find a `.overall` argument in `ard_categorical` as with `ard_stack` so if we need the overall count it would give this:

```
ARD_4 <-
  cards::bind_ard(
    ard_categorical(
      ADSL, 
      by = "ARM", 
      variables = c("SAFFL"),
      statistic = everything() ~ categorical_summary_fns("N")
    ),
    ard_categorical(
      ADSL, 
      variables = c("SAFFL"),
      statistic = everything() ~ categorical_summary_fns("N")
    ),   
    ard_categorical(
      ADSL, 
      by = "ARM", 
      variables = c("AGEGR1", "DURDSGR1"),
      statistic = everything() ~ categorical_summary_fns(c("n", "p"))
    ),
    ard_categorical(
      ADSL, 
      variables = c("AGEGR1", "DURDSGR1"),
      statistic = everything() ~ categorical_summary_fns(c("n", "p"))
    )
  )

pARD_4 <- ARD_4 %>% dplyr::filter(stat_label == "N") %>% dplyr::arrange(.cols = group1_level)
print(pARD_4)
```

With the need to compute the the analysis twice (I do admit it's not often the case but for some specific milestones it's needed).

**Comment by ddsjoberg** [comment]
Hi @aassuied-ps ! Did I answer your question? Do you want to jump on a call this week to chat about the details?

**Comment by aassuied-ps** [comment]
Hi @ddsjoberg, sorry for my late answer. I'm gonna look into it a little bit more and we can have a call after that if needed. Thanks a lot again for all your answers! : )

**Comment by ddsjoberg** [comment]
Thanks @aassuied-ps !
