### ISSUE TITLE
<Feature: Connection with rtables and tern>

### ISSUE THREAD

**Issue by pzhang-cims** [insightsengineering/cards#218]
### Feature description

Hi there,

Thanks for publishing this package and I have been knowing ARD structure for a while. I also previously experienced the usage of {rtables}, where I find their existing function of as_result_df (while this might not exactly the ARD stucture) and previous as_ard() function mentioned in https://arxiv.org/pdf/2306.16610.pdf. I'm wondering if the connection between {rtables}, {tern} and {teal}, and {cards} is also the plan of this package? Otherwise, is there a package specific for that purpose? Thanks in advance.

Best,

Peng

**Comment by ddsjoberg** [comment]
Dear @pzhang-cims , Thanks for the post.

Analysis Results Datasets are meant to serve as a **prospective** calculation that occurs before any creation of a TLG. So as far as {rtables} supporting a {cards}-created ARD is not yet something on the roadmap.

I only know of two packages that support ARD-first table creation: tfmrt and gtsummary (after its next release in a few weeks). Results from both of these packages can be setup to work with {teal}.

**Comment by pzhang-cims** [comment]
@ddsjoberg Thank you Daniel for this quick turnaround and helpful information!
