### ISSUE TITLE
Make it easier to get *total* population N  ?

### ISSUE THREAD

**Issue by bzkrouse** [insightsengineering/cards#236]
This can definitely be inferred from the ard_* results but requires post processing that users will have to do each time. For example, `ard_categorical(ADSL, variables = TRTA)` gives treatment group-level n's and population Ns. For downstream use, they would need to either manipulate the rows with Ns (keeping just 1 row and renaming it to be clear it is a total N), or do some other manipulation. 

In `ard_stack()` with `.overall = TRUE` we get population-level stats for all the variables, so this would go well with those rows.

**Comment by ddsjoberg** [comment]
I just had a thought for an easy way to get the total N using the `ard_attributes()` function. We could just return a row with N as an attribute of the data frame.

**Comment by ddsjoberg** [comment]
Let's add another function to return this information

`ard_total_n()`, which would return something like:


``` r
mtcars |> 
  dplyr::mutate(..total_n.. = 1L) |> 
  cards::ard_categorical(variables = ..total_n.., statistic = ~cards::categorical_summary_fns("N")) |> 
  dplyr::select(-"variable_level")
#> {cards} data frame: 1 x 8
#>      variable   context stat_name stat_label stat fmt_fn
#> 1 ..total_n.. categori…         N          N   32      0
#> ℹ 2 more variables: warning, error
```

<sup>Created on 2024-05-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>


We also need to decide hoq this is called from `ard_stack()`.
-  include it by default for every call?
- add argument like `ard_stack(.total_n = TRUE)` ? This is our preference, with default TRUE
