### ISSUE TITLE
Factors with NA or empty levels

### ISSUE THREAD

**Issue by ddsjoberg** [insightsengineering/cards#255]
We need to add checks that factor variables do not contain `NA` levels or the levels are empty (see https://github.com/ddsjoberg/gtsummary/issues/1973).

We need to complete the following steps:
- [x] Add `check_na_factor_levels()` to standalone checks scripts.
    - @bzkrouse added here: https://github.com/ddsjoberg/standalone/blob/2a046d061b8c626f7a9595bceb07abc58d88a1bb/R/standalone-checks.R#L527C1-L527C23
- [x] @bzkrouse our checks are normally written to check for the thing we _want_ to be true. Should we update this name to `check_no_na_factor_levels()`? NAME UPDATED
- [x]  Add `check_factor_has_levels()` to standalone checks scripts.
- [x] Update the standalone checks script in {cards}
- [ ] Add `check_na_factor_levels()` and `check_empty_factor_levels()` checks to `ard_*()` functions.
    - [ ] `ard_continuous(by, strata)` 
    - [ ] `ard_categorical(by, strata)` 
    - [ ] `ard_heirarchical*(by, variables)`
    - [ ] `ard_complex(by, strata)` 
    - [ ] Add tests for `ard_total_n()`, `ard_dichotomous()`, `ard_missing()`. The above functions should catch the bad factor columns in these functions.

**Comment by ddsjoberg** [comment]
Just need to add this function

```r
check_na_factor_levels <- function(data, variables) {
  walk(
    variables,
    \(variable) {
      if (is.factor(data[[variable]]) && any(is.na(levels(data[[variable]])))) {
        cli::cli_abort(
          "Factors with {.val {NA}} levels are not allowed, which are present in column {.val {variable}}.",
          call = get_cli_abort_call()
        )
      }
    }
  )
}
```

**Comment by ddsjoberg** [comment]
We could also add this code to our checks script, so we can more easily re0use it across functions that tabulate

**Comment by jtalboys** [comment]
Hi @ddsjoberg, myself and @ines-gimeno-molina were looking at picking up the remaining tasks here as a good introduction to the package if that would help? 

I might be missing something but does the `check_empty_factor_levels()` function still need adding to the standalone checks?

**Comment by jtalboys** [comment]
> Hi @ddsjoberg, myself and @ines-gimeno-molina were looking at picking up the remaining tasks here as a good introduction to the package if that would help?
> 
> I might be missing something but does the `check_empty_factor_levels()` function still need adding to the standalone checks?

Sorry I see it's there as `check_factor_has_levels`!

**Comment by ddsjoberg** [comment]
@jtalboys great! Let me know if you have any questions!

**Comment by ddsjoberg** [comment]
@jtalboys @ines-gimeno-molina

FYI I think we made an update to the standalone function in the standalone repo that are going to require additional updates to the package if the entire script were added to {cards} using `usethis::use_standalone()`. For this issue, it would probably be easiest to simply copy and paste these function into the existing checks script.
