### ISSUE TITLE
How to design an `ard_stack()`-like function for heirarchies?

### ISSUE THREAD

**Issue by ddsjoberg** [insightsengineering/cards#314]
@laywang142 will fill this in with the details! This could also encompass the solution for #302

**Comment by laywang142** [comment]
Current "issue": Creating hierarchical ARDs requires a lot of the same/similar steps to be done repeatedly by the user and it can be confusing/tedious when trying to create many ARDs for QC purposes. Before simplifying the process, we need to know: 
- [ ] A) What kinds of tables have this kind of layout and how relevant they are (are they generally going to be checked during the QC process. It may be best to focus on things that people have a dire need for?)
- [ ] B) How many/what kinds of datasets are required to create these nested tables and how generalizable are the filtering conditions for each one? We know for AE tables that at least two need to be included (adsl and adae) but not all the filters specified can be applied to both datasets. 
- [ ] b.1) On a related note, how consistent are the variable names across datasets? If we expect to filter on one variable in adsl, can we expect to be able to use the same variable and conditions in adae? 
- [ ] C) the "overall" column. a simple option to add one exists for in `ard_stack()` and it would be nice to have that for hierarchies

**Comment by ddsjoberg** [comment]
Hi @laywang142 , We're presenting ARDs to ADS on Oct 10. Do you think we can get this design done in the next 2 weeks, giving us 2 weeks to write the function and get it reviewed?

**Comment by laywang142** [comment]
So from what I've gathered, most of the tables and layouts are pretty standardized, which makes it a bit easier to identify the kinds of tables that need certain kinds of layouts. All of the tables are listed on the [insightsengineering tlg-catalog](https://insightsengineering.github.io/tlg-catalog/stable/tables/adverse-events/aet01.html). 

As for filtering, current tlg generation packages (like `chevron`) require that users do the filtering and alterations on their own before passing the data to the functions, so maybe we can just do that too

**Comment by laywang142** [comment]
Prefer one single dataset being passed into the ard_hierarchal_stack() call and then pass it into the function. If you need more datasets/different subsets, just call it again and you can stack them together if you want later

**Comment by laywang142** [comment]
published a document listing the specifics for the new function on RPubs ([link](https://rpubs.com/l_wang/ard-heirarchical-stack)) 

the doc also includes the arguments: `.id` and `.overallrow` which weren't included in the og description of the function.

**Comment by laywang142** [comment]
@edelarua In your work, have you thought about how to account for a situation in which you have multiple levels of a hierarchy  but only want to perform calculations on the lowest level? (example below) If so, do you have any suggestions for how to deal with it? Thanks. 
![image](https://github.com/user-attachments/assets/4915dd46-2d6f-410b-adf9-db55a9be80ee)

**Comment by edelarua** [comment]
Hi @laywang142,

I've been using a pseudo version of `ard_stack_hierarchical()` while developing `tbl_hierarchical()` that I've copied below, which develops and calls the `ard_hierarchical()` calls within the function. I haven't done any refinement yet so it's returning much more than is needed right now, but ideally, the `include` argument will be used to specify which levels to return calculations for. I also have not yet considered how overall row calculations should be done.

Let me know your thoughts!! I can make modifications to my work on `tbl_hierarchical()` as needed.

```r
ard_stack_hierarchical <- function(data,
                                   hierarchies,
                                   by = NULL,
                                   id = NULL,
                                   include,
                                   statistic,
                                   denominator,
                                   .overall = FALSE,
                                   .missing = FALSE,
                                   .attributes = FALSE,
                                   .total_n = FALSE,
                                   .shuffle = FALSE) {
# outermost level  
ard_lvls <- list(
    cards::ard_hierarchical(
      data = data,
      variables = tail(hierarchies, 1),
      by = all_of(by),
      statistic = statistic,
      denominator = denominator,
      id = all_of(id)
    )
  )

  for (i in seq_along(hierarchies)) {
    ard_lvls <- c(
      ard_lvls,
      list(
        # innermost level (to be refined)
        cards::ard_hierarchical(
          data = data,
          variables = hierarchies[1:i],
          by = all_of(by),
          statistic = statistic,
          denominator = denominator,
          id = all_of(id)
        ),
        if (i != 1 && i != length(hierarchies)) {
          # intermediate levels
          cards::ard_hierarchical(
            data = data,
            variables = hierarchies[-i],
            by = all_of(by),
            statistic = statistic,
            denominator = denominator,
            id = all_of(id)
          )
        } else {
          NULL
        }

      )
    )
  }

  ard_lvls |>
    dplyr::bind_rows() |>
    cards::tidy_ard_column_order() |>
    cards::tidy_ard_row_order()
}
```

**Comment by ddsjoberg** [comment]
hey hey @laywang142 @edelarua !

FYI the glue package will be releasing a breaking change for gtsummary soon (technically, should be no less than 2 weeks from now). As a result, we need to release cards and gtsummary as well (sooner than anticipated).

Let's plan to include this function in that upcoming release.

**Comment by ddsjoberg** [comment]
Thank you so much for this function @edelarua ! ❤️

**Comment by edelarua** [comment]
@ddsjoberg this should be doable. I think [my current design](https://github.com/ddsjoberg/gtsummary/tree/1872-tbl_heirarchical) is working well so far (for the most part). We just need to figure out a few arguments and refine `ard_stack_hierarchical()` a bit so that it uses `ard_stack` and can be used for overall rows, but it shouldn't be too much trouble.

**Comment by ddsjoberg** [comment]
Great! @edelarua if you can continue to focus on the gtsummary function, I can work on this one using your function as the template, then we can combine. I'll def need your review before merging to ensure it meets your needs in the gtsummary function.
