### ISSUE TITLE
`rename_ard_columns()` unlist behavior adjustment

### ISSUE THREAD

**Issue by laywang142** [insightsengineering/cards#332]
### Feature description

Currently, `rename_ard_columns()`'s unlist behavior is that it'll not unlist if it encounters NULLs. There are workarounds but I was wondering if it could just impute NA's for me (where it makes sense) and then just leave a message saying that it did so. 

For context, I've been working on qc-ing tlgs using cards/ARDs and unlisting the `stats` values is something I do as part of the process to compare the numeric values of things. 

Feel free to ping me if the request isn't clear.

**Comment by ddsjoberg** [comment]
Thanks for the post @laywang142 !

I think that is something we can add. In the meantime have you seen the `replace_null_statistic()` function?

``` r
data.frame(x = rep_len(NA_character_, 10)) |>
  cards::ard_continuous(
    variables = x,
    statistic = ~ cards::continuous_summary_fns(c("median", "p25", "p75"))
  ) |>
  cards::replace_null_statistic()
#> {cards} data frame: 3 x 8
#>   variable   context stat_name stat_label stat     error
#> 1        x continuo…    median     Median   NA          
#> 2        x continuo…       p25         Q1   NA non-nume…
#> 3        x continuo…       p75         Q3   NA non-nume…
#> ℹ 2 more variables: fmt_fn, warning
```

<sup>Created on 2024-09-27 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
