### ISSUE TITLE
How to specify the correct call env for cli errors?

### ISSUE THREAD

**Issue by ddsjoberg** [insightsengineering/cards#42]
The cards package will likely be called by other packages, but it will be important for the errors to be linked to the appropriate, user-facing function. For example, if we wrote a function that creates forest plots and we wanted an ARD back-end, we would likely  write a function that called `cardx::ard_regression()` and a user may not know the cards package even exists.

One solution is to export a function that saves the fn env during the execution, so we can always report the correct env. Example below. But is this all too much just for slightly better messaging?

``` r
# set this function at the top of a user-facing function
set_cli_abort_call <- function(env = rlang::caller_env()) {
  if (getOption("cli_abort_call") |> is.null()) {
    options(cli_abort_call = env)
    withr::defer(expr = options(cli_abort_call = NULL), envir = env)
  }
  invisible()
}

# use this function in `cli_abort(call=get_cli_abort_call())`
get_cli_abort_call <- function() {
  getOption("cli_abort_call", default = parent.frame())
}

# function called by user
user_facing_function <- function() {
  set_cli_abort_call()
  check_for_errors()
}

# an internal function OR exported function from another pkg that throws the error
check_for_errors <- function() {
  cli::cli_abort(
    c("!" = "This is an error!", 
      "i" = "Be better"), 
    call = get_cli_abort_call()
  )
}

# this exhibits the user experience
user_facing_function()
#> Error in `user_facing_function()`:
#> ! This is an error!
#> ℹ Be better

# check the default still work when no option is set
check_for_errors()
#> Error in `check_for_errors()`:
#> ! This is an error!
#> ℹ Be better
```

<sup>Created on 2024-01-30 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
When it comes time to implement this, we'll add the `set_cli_abort_call()` and `get_cli_abort_call()` functions to the standalone checks file in `ddsjoberg/standalone`. We'll change all the default `call=` arguments to the `get_cli_abort_call()` function. Then every call to `cli::cli_abort()` that may appear in the package must also be updated. Same goes for {cardx}.

I am not sure if gtsummary will be ready for the update yet.

- Is there a better, shorter name for these functions?
- What is a good name for the option?

**Comment by ddsjoberg** [comment]
@shajoezhu I think we can prioritize this in the next PI session. What do you think?

**Comment by shajoezhu** [comment]
let's do it!

**Comment by ddsjoberg** [comment]
@edelarua I think these set and get cli call functions should be placed at the top of this script
https://github.com/ddsjoberg/standalone/blob/main/R/standalone-checks.R

If everything works properly, then we'd want to change the default call argument for every `check_*()` function to be the get function.

Do we need to add the withr dep? https://github.com/r-lib/withr/blob/main/NEWS.md
