### ISSUE TITLE
Allow variables = NULL in ard_categorical

### ISSUE THREAD

**Issue by bzkrouse** [insightsengineering/cards#54]
### Feature description

This would allow for calculating counts on `by` or `strata` variables, yielding more consistency  in the results, as opposed to requiring these variables to be passed to the `variables` argument.

**Comment by ddsjoberg** [comment]
I think a wrapper for `ard_categorical()` could be good in this case, as specifying `variables = NULL` could be confusing for users?

Perhaps something like this:

```r
ard_hierarchical_count(by = "ARM", hierarchy = c("AESOC", "AETERM"))
```

```r
ard_hierarchical_count(by = c("ARM", "AEGRADE"), hierarchy = c("AESOC", "AETERM"))
```

We could optionally include a `denominator=` argument for the percentage calculations.

The resulting card could look like this:

![image](https://github.com/insightsengineering/cards/assets/26774684/0fb8e377-9a34-4510-a775-2b4dea4e5e4b)

**Comment by ddsjoberg** [comment]
Add argument to get counts for all the nested hierarchies, eg. `c(AESOC, AETERM)`, then `c(AESOC)` only. There are some tables in a CSR where we don't want these, so need to be able to turn it off

**Comment by ddsjoberg** [comment]
Example APIs?

Typical AE summary with denom 
```r
bind_ard(
  ADAE |>
    filter(AETERMF == "Y") |>
    ard_hierarchical_count(by = "ARM", variables = c("AESOC", "AETERM"), denom = ADSL),
  ADAE |>
    filter(AESOCF == "Y") |>
    ard_hierarchical_count(by = "ARM", variables = "AESOC", denom = ADSL)
)
```

Report AE counts (no denoms) Perhaps we can make this its own separate function that counts all of the hierarchies and stacks them for the user. They would also not be required to specify the statistics argument.
```r
bind_ard(
  ADAE |>
    ard_hierarchical_count(by = "ARM", variables = c("AESOC", "AETERM"), statistic = ~default_categorical("n")),
  ADAE |>
    ard_hierarchical_count(by = "ARM", variables = "AESOC", statistic = ~default_categorical("n"))
)
```
