### ISSUE TITLE
What to do about rounding?

### ISSUE THREAD

**Issue by ddsjoberg** [insightsengineering/cards#69]
@bzkrouse do you have a preference on how rounding like 2.5 should be handled? Default R rounds this to 2 with the "round-to-even" method, and the rest of the world would likely round this to 3.  

In our group, we've decided to go with the standard rounding we all learned in elementary school, so 2.5 would be rounded to 3.

**Comment by bzkrouse** [comment]
In {tfrmt} we are just using the default rounding in R with no additional options (the user can always pass custom formatting functions more generally).
If {cards} does have a default that deviates from R's default, will that be interpreted as matching SAS, and if so, will users then expect the same of other default calculations (e.g. quantiles)?

**Comment by ddsjoberg** [comment]
> In {tfrmt} we are just using the default rounding in R with no additional options (the user can always pass custom formatting functions more generally).

Ah ok, so you're not utilizing the `statistic_fmt` column, you're taking the the numeric results and formatting in `tfrmt` ?

> If {cards} does have a default that deviates from R's default, will that be interpreted as matching SAS, and if so, will users then expect the same of other default calculations (e.g. quantiles)?

This issue primarily relates to the default formatting function that we assign in `statistic_fmt_fn`. It sounds like you may not be using this at all in tfmrt, though. Currently, the default for, for example, the `N` statistic is `function(x) format(round(x, digits = 0), nsmall = 0)` which uses R's round-to-even default. We can simply replace `round()` with another function that performs classic rounding that would match SAS's results. What I like about this option is that we don't need to have a conversation about round-to-even because the results will just be as people expect them to be. Users can change the formatting functions with the `fmt_fn=` argument.

I think as much as we can align with SAS by default that is beneficial, for example, on quantile computation. At the moment we don't have any functions for quantiles, so I am not sure this is an issue for now?

**Comment by bzkrouse** [comment]
"Ah ok, so you're not utilizing the statistic_fmt column, you're taking the the numeric results and formatting in tfrmt ?" Yep!

For quantiles, I was thinking of the percentiles that are available in the default continuous stats. In general, I think either choice is fine as long as it's clear/consistent and people have the ability to customize (which they will!)

**Comment by ddsjoberg** [comment]
OK! Then the points about default rounding can be dealt with in downstream packages :)

Agree, let's add p25 and p75 to the default continuous function.
