### ISSUE TITLE
ard_categorical() with statistics = "p" also retains "n" and "N" in results

### ISSUE THREAD

**Issue by bzkrouse** [insightsengineering/cards#72]
### Feature description

as a user, I would expect only the "p" to be returned, even if the others are being calculated under the hood

**Comment by ddsjoberg** [comment]
Since we need n and N to calculate p, i just kept them with the return. Is it detrimental to return for tfrmt users?

**Comment by bzkrouse** [comment]
That is totally reasonable! To be more specific, I think users will often want to filter out the variable level denominator "N" in favor of the header N's, and simply display n (%) in the table. But if it is the intent to keep it comprehensive then that makes sense.

**Comment by ddsjoberg** [comment]
In a tfmrt workflow, is there an issue keeping a stat that doesn't go in the table? 🤔🤔 

We could remove them in the returned data frame. I thought about keeping them for the reusability of the ARD for other tables or a figure representation of results. Also, in this case, the N is the number of non-missing observations, and may not match the Ns from the header row

**Comment by bzkrouse** [comment]
tfrmt includes all rows in the data (which is conducive to the way the values formatting is applied - very generally across the whole dataset, and only *specific* when needed) so a subset has to be performed in advance.  
I was thinking people might expect only the statistics they requested, like the way ard_continuous `statistics` argument works. But I understand this can lead to misinterpretation of results...however by that argument would we want to keep the N for continuous too??

**Comment by ddsjoberg** [comment]
To be clear, I am 100% ok with only returning the statistics requested. I just kept stats that were required to calculate requested stats (e.g. keep N as it's required to calculate p), because I saw no drawback to keeping them and they would be available for future use.

If there is a drawback, however, for tfrmt use, we can update!

**Comment by ddsjoberg** [comment]
DECISION: Only return stats that users requested, so if a secondary stat is required we will delete before returning the ARD data frame

**Comment by ddsjoberg** [comment]
Hmmm, this is going to be unexpectedly tricky 🤔 

Looking at the example below. Because the n, p, and N are functions of one another, we're using the method where this single "tabulate" function returns a named list of results (those names are n, p, and N). But I don't think there will be an easy way to get at the "requested" stats only....I am stumped for now on how to get at this.....

``` r
library(cards)
compute_formula_selector(mtcars["cyl"], x = everything() ~ categorical_variable_summary_fns())
#> $cyl
#> $cyl$tabulate
#> function(x, stats = summaries) {
#> 
#>       res <- list()
#>       if (any(c("N", "p") %in% stats))
#>         res[["N"]] <- length(x)
#>       if (any(c("n", "p") %in% stats))
#>         res[["n"]] <- table(x)
#>       if ("p" %in% stats)
#>         res$p <- res$n / res$N
#> 
#>       res
#>     }
#> <bytecode: 0x106760678>
#> <environment: 0x10676dde0>
```

<sup>Created on 2023-12-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
To clarify the above post, it is indeed simple to only return the requested stats from `categorical_variable_summary_fns()` (the last line in the function can be updated to `res[stats]`). 

BUT, if the user requests only the percent to be returned AND passes the `ard_categorical(denominator)`, we're in a trickier spot. We'd need to go back and calculate the `n`s on the primary dataset, then get the `N`s from `denominator, and return the re-calculated `p` and only the `p`. It seems silly to recalculate the `n` in a situation like this...

@bzkrouse any ideas? Would it be cumbersome to allow an ARD to contain a statistic that does not appear in the final tfrmt table?

**Comment by bzkrouse** [comment]
@ddsjoberg thanks for looking into this, and the challenges make total sense. So maybe the best solution is to leave it as-is but clarify the behavior and expected result in the documentation?

**Comment by ddsjoberg** [comment]
Will do! added this in #82
