### ISSUE TITLE
Review `ard_dichotomous()`

### ISSUE THREAD

**Issue by ddsjoberg** [insightsengineering/cards#81]
@ddsjoberg merged this without a review! @bzkrouse will review the new fn

**Comment by bzkrouse** [comment]
@ddsjoberg now that you are filling variable_level for N's, is there a situation where variable_level will be NULL (see [line 49](https://github.com/insightsengineering/cards/blob/main/R/ard_dichotomous.R#L49))? I don't think it hurts but I just wanted to check in case something unexpected happens.

**Comment by ddsjoberg** [comment]
ahh, good point, thanks!! I updated in `main`
