### ISSUE TITLE
groupX_level values for statistical tests

### ISSUE THREAD

**Issue by bzkrouse** [insightsengineering/cards#85]
### Feature description

Currently ard_ttest, ard_chisqtest, etc. only output a group variable (e.g. `group1`) but no group value. Consider filling the group level value (e.g. `group1_level`) with a placeholder string (could be user-supplied) so that results continue to be meaningful after `shuffle_ard()` (see #62)

**Comment by ddsjoberg** [comment]
What kind of placeholder do you have in mind?

In the t-test results, we include `group1_level`, but it's only populated when it's meaningful.

![image](https://github.com/insightsengineering/cards/assets/26774684/1e26c862-9b16-43d3-8d70-17fa5a6c2afc)

**Comment by ddsjoberg** [comment]
Similarly, would you need `variable_levels` populated with something for continuous variable summaries (as an example).

**Comment by ddsjoberg** [comment]
@bzkrouse is this something that needs to be addressed before the first release? if so, can you add the milestone? thanks! 🏁

**Comment by bzkrouse** [comment]
@ddsjoberg Maybe something like "..overall.."..? It'd be great to chat about this further!

**Comment by ddsjoberg** [comment]
`shuffle_ard()` will populate the "overall" label as needed

**Comment by ddsjoberg** [comment]
added with `shuffle_ard()`
